### ISSUE TITLE
Validate task launches aren't interrupted when Maven artifactory is down

### ISSUE THREAD

**Issue by sabbyanandan** [spring-cloud/spring-cloud-deployer-cloudfoundry#361]
- [x] If Maven caching is [enabled](https://docs.pivotal.io/scdf/1-9/managing-service-instances.html#enabling-maven-artifact-caching), verify whether the task launch is prevented
- [x] When Maven artifactory is down, verify whether task launch is prevented or not on CF (for the same task; droplet already exist)

**Comment by jvalkeal** [comment]
`maven-cache` setting is slightly misleading as it just instructs deployer and tasklauncher not to delete maven artifact when it's done with it.

However it looks like a way `MavenResource` works is that if file is in place, resolver doesn't fail. Update policy is not set and that in maven defaults something called `never`.

**Comment by jvalkeal** [comment]
Just leaving few notes here how to "break" maven repo to test these scenarios, i.e on CF:

Use `reposilite` as an app to proxy maven, use manifest below to push it:
```
---
applications:
  - name: reposilite-server
    host: reposilite-server
    memory: 2G
    disk_quota: 2G
    instances: 1
    timeout: 180
    path: reposilite-2.9.4.jar
    env:
      JAVA_OPTS: -Dreposilite.port=8080 -Dreposilite.proxied=https://repo.spring.io/libs-snapshot

```

When pushing dataflow/skipper replace default maven repo per:
```
         "maven" : {
            "remoteRepositories" : {
              "springRepo" : {
                "url" : "http://reposilite-server.apps.<cf domain>"
              }
            }
          }, 

```

Then you can stop `reposilite` instance and you don't no longer have working maven system.
